from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func
from app.core.database import Base


class AppSettings(Base):
    """Key-value store for application-wide settings (scheduler, AI, preferences)."""
    __tablename__ = "app_settings"

    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(100), unique=True, nullable=False, index=True)
    value = Column(Text, nullable=True)
    value_type = Column(String(20), default="string")  # string, int, float, bool
    category = Column(String(50), nullable=True)        # scheduler, ai, general
    label = Column(String(200), nullable=True)
    description = Column(Text, nullable=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


# Default settings seeded on first startup
DEFAULT_APP_SETTINGS = [
    {
        "key": "price_update_interval_minutes",
        "value": "30",
        "value_type": "int",
        "category": "scheduler",
        "label": "Price Update Interval (minutes)",
        "description": "How often asset prices are refreshed from market APIs.",
    },
    {
        "key": "eod_snapshot_hour",
        "value": "13",
        "value_type": "int",
        "category": "scheduler",
        "label": "EOD Snapshot Hour (UTC)",
        "description": "Hour (UTC, 0-23) when the daily portfolio snapshot is captured. 13 UTC = 6:30 PM IST.",
    },
    {
        "key": "eod_snapshot_minute",
        "value": "30",
        "value_type": "int",
        "category": "scheduler",
        "label": "EOD Snapshot Minute",
        "description": "Minute (0-59) for the daily portfolio snapshot.",
    },
    {
        "key": "news_morning_hour",
        "value": "9",
        "value_type": "int",
        "category": "scheduler",
        "label": "Morning News Hour (IST)",
        "description": "IST hour (0-23) for the morning AI news alert run.",
    },
    {
        "key": "news_evening_hour",
        "value": "18",
        "value_type": "int",
        "category": "scheduler",
        "label": "Evening News Hour (IST)",
        "description": "IST hour (0-23) for the evening AI news alert run.",
    },
    {
        "key": "news_limit_per_user",
        "value": "10",
        "value_type": "int",
        "category": "scheduler",
        "label": "News Assets per Run",
        "description": "Maximum number of portfolio assets analysed per user in each scheduled news run.",
    },
    {
        "key": "ai_news_provider",
        "value": "openai",
        "value_type": "string",
        "category": "ai",
        "label": "AI News Provider",
        "description": "Which AI provider to use: openai, grok, gemini, anthropic, deepseek, mistral.",
    },
    # ── AI API Keys (empty = fall back to .env) ──
    {
        "key": "ai_openai_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "OpenAI API Key",
        "description": "API key for OpenAI. Leave blank to use the .env value.",
    },
    {
        "key": "ai_grok_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "Grok API Key",
        "description": "API key for Grok (xAI). Leave blank to use the .env value.",
    },
    {
        "key": "ai_gemini_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "Google Gemini API Key",
        "description": "API key for Google Gemini.",
    },
    {
        "key": "ai_anthropic_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "Anthropic Claude API Key",
        "description": "API key for Anthropic Claude.",
    },
    {
        "key": "ai_deepseek_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "DeepSeek API Key",
        "description": "API key for DeepSeek.",
    },
    {
        "key": "ai_mistral_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "Mistral API Key",
        "description": "API key for Mistral AI.",
    },
    # ── AI API Endpoints ──
    {
        "key": "ai_openai_endpoint",
        "value": "https://api.openai.com/v1/chat/completions",
        "value_type": "string",
        "category": "ai",
        "label": "OpenAI Endpoint",
        "description": "OpenAI API endpoint URL.",
    },
    {
        "key": "ai_grok_endpoint",
        "value": "https://api.x.ai/v1/chat/completions",
        "value_type": "string",
        "category": "ai",
        "label": "Grok Endpoint",
        "description": "Grok API endpoint URL.",
    },
    {
        "key": "ai_gemini_endpoint",
        "value": "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
        "value_type": "string",
        "category": "ai",
        "label": "Gemini Endpoint",
        "description": "Gemini OpenAI-compatible endpoint URL.",
    },
    {
        "key": "ai_anthropic_endpoint",
        "value": "https://api.anthropic.com/v1/messages",
        "value_type": "string",
        "category": "ai",
        "label": "Anthropic Endpoint",
        "description": "Anthropic Messages API endpoint URL.",
    },
    {
        "key": "ai_deepseek_endpoint",
        "value": "https://api.deepseek.com/chat/completions",
        "value_type": "string",
        "category": "ai",
        "label": "DeepSeek Endpoint",
        "description": "DeepSeek API endpoint URL.",
    },
    {
        "key": "ai_mistral_endpoint",
        "value": "https://api.mistral.ai/v1/chat/completions",
        "value_type": "string",
        "category": "ai",
        "label": "Mistral Endpoint",
        "description": "Mistral API endpoint URL.",
    },
    # ── AI Model Names ──
    {
        "key": "ai_openai_model",
        "value": "gpt-3.5-turbo",
        "value_type": "string",
        "category": "ai",
        "label": "OpenAI Model",
        "description": "OpenAI model name.",
    },
    {
        "key": "ai_grok_model",
        "value": "grok-beta",
        "value_type": "string",
        "category": "ai",
        "label": "Grok Model",
        "description": "Grok model name.",
    },
    {
        "key": "ai_gemini_model",
        "value": "gemini-2.0-flash",
        "value_type": "string",
        "category": "ai",
        "label": "Gemini Model",
        "description": "Gemini model name.",
    },
    {
        "key": "ai_anthropic_model",
        "value": "claude-sonnet-4-20250514",
        "value_type": "string",
        "category": "ai",
        "label": "Anthropic Model",
        "description": "Anthropic Claude model name.",
    },
    {
        "key": "ai_deepseek_model",
        "value": "deepseek-chat",
        "value_type": "string",
        "category": "ai",
        "label": "DeepSeek Model",
        "description": "DeepSeek model name.",
    },
    {
        "key": "ai_mistral_model",
        "value": "mistral-small-latest",
        "value_type": "string",
        "category": "ai",
        "label": "Mistral Model",
        "description": "Mistral model name.",
    },
    # ── Free Alert Sources ──
    {
        "key": "finnhub_api_key",
        "value": "",
        "value_type": "secret",
        "category": "ai",
        "label": "Finnhub API Key (Free Tier)",
        "description": "Optional free API key from finnhub.io for stock news alerts. Get one at https://finnhub.io/register",
    },
    {
        "key": "free_alerts_enabled",
        "value": "true",
        "value_type": "bool",
        "category": "scheduler",
        "label": "Free Alerts Enabled",
        "description": "Enable RSS news feeds and price-based portfolio alerts (no API key required).",
    },
    {
        "key": "session_timeout_minutes",
        "value": "30",
        "value_type": "int",
        "category": "general",
        "label": "Session Timeout (minutes)",
        "description": "Idle time before the user session expires and requires re-login.",
    },
    {
        "key": "monthly_contribution_day",
        "value": "1",
        "value_type": "int",
        "category": "scheduler",
        "label": "Monthly Contribution Day",
        "description": "Day of the month (1-28) when automatic PF contributions and Gratuity updates run.",
    },
    {
        "key": "monthly_contribution_hour",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "Monthly Contribution Hour (UTC)",
        "description": "UTC hour (0-23) for the monthly PF/Gratuity job. 0 UTC = 5:30 AM IST.",
    },
    {
        "key": "monthly_contribution_minute",
        "value": "30",
        "value_type": "int",
        "category": "scheduler",
        "label": "Monthly Contribution Minute",
        "description": "Minute (0-59) for the monthly PF/Gratuity job.",
    },
    # ── Market Insight Scheduler Settings ──
    {
        "key": "forex_refresh_hour",
        "value": "9",
        "value_type": "int",
        "category": "scheduler",
        "label": "Forex Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for daily foreign currency value refresh. 9 UTC = 2:30 PM IST.",
    },
    {
        "key": "forex_refresh_minute",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "Forex Refresh Minute",
        "description": "Minute (0-59) for daily forex refresh.",
    },
    {
        "key": "macro_data_refresh_day",
        "value": "1",
        "value_type": "int",
        "category": "scheduler",
        "label": "Macro Data Refresh Day",
        "description": "Day of month (1-28) for macro-economic data refresh (US CPI, unemployment, India CPI, VIX, PE, FII/DII, SIP).",
    },
    {
        "key": "macro_data_refresh_hour",
        "value": "6",
        "value_type": "int",
        "category": "scheduler",
        "label": "Macro Data Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for monthly macro data refresh. 6 UTC = 11:30 AM IST.",
    },
    {
        "key": "rbi_rate_refresh_day",
        "value": "10",
        "value_type": "int",
        "category": "scheduler",
        "label": "RBI Rate Refresh Day",
        "description": "Day of month (1-28) for bimonthly RBI repo rate scrape (runs in Feb, Apr, Jun, Aug, Oct, Dec).",
    },
    {
        "key": "rbi_rate_refresh_hour",
        "value": "9",
        "value_type": "int",
        "category": "scheduler",
        "label": "RBI Rate Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for RBI rate scrape. 9 UTC = 2:30 PM IST.",
    },
    {
        "key": "bank_fd_refresh_day",
        "value": "1",
        "value_type": "int",
        "category": "scheduler",
        "label": "Bank FD Refresh Day",
        "description": "Day of month (1-28) for monthly bank FD rate scrape.",
    },
    {
        "key": "bank_fd_refresh_hour",
        "value": "7",
        "value_type": "int",
        "category": "scheduler",
        "label": "Bank FD Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for bank FD rate scrape. 7 UTC = 12:30 PM IST.",
    },
    {
        "key": "govt_scheme_refresh_day",
        "value": "1",
        "value_type": "int",
        "category": "scheduler",
        "label": "Govt Scheme Refresh Day",
        "description": "Day of month (1-28) for monthly government savings scheme rate scrape.",
    },
    {
        "key": "govt_scheme_refresh_hour",
        "value": "7",
        "value_type": "int",
        "category": "scheduler",
        "label": "Govt Scheme Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for govt scheme rate scrape. 7 UTC = 12:30 PM IST.",
    },
    {
        "key": "govt_scheme_refresh_minute",
        "value": "30",
        "value_type": "int",
        "category": "scheduler",
        "label": "Govt Scheme Refresh Minute",
        "description": "Minute (0-59) for govt scheme rate scrape.",
    },
    {
        "key": "news_cache_refresh_minutes",
        "value": "30",
        "value_type": "int",
        "category": "scheduler",
        "label": "News Cache Refresh Interval (minutes)",
        "description": "How often the financial news cache is refreshed (in minutes).",
    },
    {
        "key": "nse_holidays_refresh_month",
        "value": "12",
        "value_type": "int",
        "category": "scheduler",
        "label": "NSE Holidays Refresh Month",
        "description": "Month (1-12) for annual NSE trading holidays refresh (seeds next year's holidays).",
    },
    {
        "key": "nse_holidays_refresh_day",
        "value": "1",
        "value_type": "int",
        "category": "scheduler",
        "label": "NSE Holidays Refresh Day",
        "description": "Day of month for annual NSE holidays refresh.",
    },
    {
        "key": "mmi_morning_hour",
        "value": "3",
        "value_type": "int",
        "category": "scheduler",
        "label": "India MMI Morning Hour (UTC)",
        "description": "UTC hour (0-23) for morning India Market Mood Index refresh. 3 UTC = 8:30 AM IST.",
    },
    {
        "key": "mmi_morning_minute",
        "value": "45",
        "value_type": "int",
        "category": "scheduler",
        "label": "India MMI Morning Minute",
        "description": "Minute (0-59) for morning MMI refresh.",
    },
    {
        "key": "mmi_afternoon_hour",
        "value": "10",
        "value_type": "int",
        "category": "scheduler",
        "label": "India MMI Afternoon Hour (UTC)",
        "description": "UTC hour (0-23) for afternoon India MMI refresh. 10 UTC = 3:30 PM IST.",
    },
    {
        "key": "mmi_afternoon_minute",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "India MMI Afternoon Minute",
        "description": "Minute (0-59) for afternoon MMI refresh.",
    },
    {
        "key": "btc_fng_hour",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "BTC Fear & Greed Hour (UTC)",
        "description": "UTC hour (0-23) for daily Bitcoin Fear & Greed Index refresh.",
    },
    {
        "key": "btc_fng_minute",
        "value": "30",
        "value_type": "int",
        "category": "scheduler",
        "label": "BTC Fear & Greed Minute",
        "description": "Minute (0-59) for BTC Fear & Greed refresh.",
    },
    {
        "key": "us_fng_open_hour",
        "value": "14",
        "value_type": "int",
        "category": "scheduler",
        "label": "US Fear & Greed Open Hour (UTC)",
        "description": "UTC hour (0-23) for US Fear & Greed refresh at market open. 14 UTC = ~9:00 AM ET.",
    },
    {
        "key": "us_fng_open_minute",
        "value": "45",
        "value_type": "int",
        "category": "scheduler",
        "label": "US Fear & Greed Open Minute",
        "description": "Minute (0-59) for US Fear & Greed market open refresh.",
    },
    {
        "key": "us_fng_close_hour",
        "value": "21",
        "value_type": "int",
        "category": "scheduler",
        "label": "US Fear & Greed Close Hour (UTC)",
        "description": "UTC hour (0-23) for US Fear & Greed refresh at market close. 21 UTC = ~4:00 PM ET.",
    },
    {
        "key": "us_fng_close_minute",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "US Fear & Greed Close Minute",
        "description": "Minute (0-59) for US Fear & Greed market close refresh.",
    },
    {
        "key": "liquidity_refresh_day_of_week",
        "value": "mon",
        "value_type": "string",
        "category": "scheduler",
        "label": "Liquidity Refresh Day of Week",
        "description": "Day of week for weekly global liquidity data refresh (mon, tue, wed, thu, fri, sat, sun).",
    },
    {
        "key": "liquidity_refresh_hour",
        "value": "2",
        "value_type": "int",
        "category": "scheduler",
        "label": "Liquidity Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for weekly liquidity data refresh (FRED M2 + Yahoo Finance).",
    },
    {
        "key": "mf_systematic_plan_hour",
        "value": "4",
        "value_type": "int",
        "category": "scheduler",
        "label": "MF Systematic Plan Hour (UTC)",
        "description": "UTC hour (0-23) for daily MF systematic plan execution (SIP/STP/SWP). 4 UTC = 9:30 AM IST.",
    },
    {
        "key": "mf_systematic_plan_minute",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "MF Systematic Plan Minute",
        "description": "Minute (0-59) for MF systematic plan execution.",
    },
    # ── FRED API Key ──
    {
        "key": "fred_api_key",
        "value": "",
        "value_type": "secret",
        "category": "api_keys",
        "label": "FRED API Key",
        "description": "API key for Federal Reserve Economic Data (fred.stlouisfed.org). Used for Global Liquidity Insight (M2 money supply data). Free key at fred.stlouisfed.org/docs/api/api_key.html",
    },
    # ── Market Data API Keys ──
    {
        "key": "cmc_api_key",
        "value": "",
        "value_type": "secret",
        "category": "api_keys",
        "label": "CoinMarketCap API Key",
        "description": "API key for CoinMarketCap (pro-api.coinmarketcap.com). Used for Bitcoin Fear & Greed Index. Free tier available at coinmarketcap.com/api.",
    },
    {
        "key": "alpha_vantage_api_key",
        "value": "",
        "value_type": "secret",
        "category": "api_keys",
        "label": "Alpha Vantage API Key",
        "description": "API key for Alpha Vantage (alphavantage.co). Used for US stock market data. Free tier available at alphavantage.co/support/#api-key.",
    },
    {
        "key": "rapidapi_key",
        "value": "",
        "value_type": "secret",
        "category": "api_keys",
        "label": "RapidAPI Key",
        "description": "API key for RapidAPI (rapidapi.com). Used for various market data endpoints.",
    },
    # ── AI Models Cache Scheduler ──
    {
        "key": "ai_models_refresh_hour",
        "value": "1",
        "value_type": "int",
        "category": "scheduler",
        "label": "AI Models Refresh Hour (UTC)",
        "description": "UTC hour (0-23) for daily refresh of available AI models list. 1 UTC = 6:30 AM IST.",
    },
    {
        "key": "ai_models_refresh_minute",
        "value": "0",
        "value_type": "int",
        "category": "scheduler",
        "label": "AI Models Refresh Minute",
        "description": "Minute (0-59) for daily AI models refresh.",
    },
]
