"""add_demat_accounts_table

Revision ID: 638328b96730
Revises: 6c64e6666c62
Create Date: 2026-02-15 13:14:19.785066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638328b96730'
down_revision = '6c64e6666c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('demat_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'demat_accounts', ['demat_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'demat_account_id')
    # ### end Alembic commands ###