"""add_account_fields_to_assets

Revision ID: 657cf303af8e
Revises: 753a2500fedc
Create Date: 2026-02-13 13:24:02.298933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657cf303af8e'
down_revision = '753a2500fedc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('statement_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('broker_name', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('account_holder_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_assets_account_id'), 'assets', ['account_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'statements', ['statement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_account_id'), table_name='assets')
    op.drop_column('assets', 'account_holder_name')
    op.drop_column('assets', 'broker_name')
    op.drop_column('assets', 'account_id')
    op.drop_column('assets', 'statement_id')
    # ### end Alembic commands ###