"""add_mutual_fund_holdings_table

Revision ID: 68eca3fa4082
Revises: e1f2a3b4c5d6
Create Date: 2026-02-17 13:34:30.300733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eca3fa4082'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crypto_accounts_id'), 'crypto_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_accounts_id'), table_name='crypto_accounts')
    # ### end Alembic commands ###