"""add_bank_accounts_and_expense_tracking

Revision ID: cf70a5dc799b
Revises: 92808804c3ea
Create Date: 2026-02-13 22:57:09.052370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf70a5dc799b'
down_revision = '92808804c3ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###